# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='friend',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name1',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
