# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Reg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
    ]
